#!/usr/bin/env python3
"""Local init/update/build entrypoint through one deployment implementation."""
import argparse
import json
from pathlib import Path
import subprocess
import tempfile

import build_bundle
import deployment
import migration


def ignores(target, bound, mode, adaptations, resolutions):
    adaptations, resolutions = dict(adaptations), dict(resolutions or {})
    path = deployment.safe(target, ".gitignore")
    before = path.read_bytes() if path.exists() else b""
    content = before.decode("utf-8-sig")
    required = [".mt-agent-devkit-migration.lock", ".mt-agent-devkit-migration.lock.recovering"]
    if mode == "strict":
        required += [".mt-agent-devkit/"] + [values["PROVIDER_ROOT"] + "/" for values in bound.values()]
    else:
        required += [values["RUNTIME_ROOT"] + "/" + folder + "/" for values in bound.values() for folder in ("memory", "working-record", "retros", "tmp", "internal", "docs")]
    existing = set(content.splitlines())
    missing = [line for line in required if line not in existing]
    if missing:
        content += ("\n" if content and not content.endswith("\n") else "") + "\n".join(missing) + "\n"
    adaptations[".gitignore"] = content
    if before:
        resolutions[".gitignore"] = {"before_sha256": deployment.digest(before), "after_sha256": deployment.digest(content.encode()), "reason": "Append exact managed runtime ignores; preserve all existing project patterns"}
    return adaptations, resolutions


def local(target, devkit_root, provider, mode, profile, adaptations, resolutions=None, apply=False):
    target, devkit_root = Path(target), Path(devkit_root)
    previous = deployment.inspect(target)["receipt"]
    bound = dict(previous["providers"]) if previous else {}
    bound.setdefault(provider, {"PROVIDER_ROOT": "." + provider, "RUNTIME_ROOT": "." + provider + "/agents", "COMMAND_ROOT": "." + provider + "/agents"})
    adaptations, resolutions = ignores(target, bound, mode, adaptations, resolutions)
    if not previous:
        legacy = migration.inventory(target, [p for p in deployment.PROVIDERS if (target / ("." + p) / "agents").exists()])
        if legacy["mode"] and legacy["mode"] != mode:
            raise deployment.Conflict("legacy mode switching excluded")
        _, candidates = migration.review_candidates(target, legacy["providers"])
        for path, candidate in candidates.items():
            if path not in adaptations:
                raise deployment.Conflict("review legacy content before migration: " + path)
        # Approved content is explicit; preserved runtime never enters adaptations.
    with tempfile.TemporaryDirectory() as folder:
        bundle = Path(folder)
        build_bundle.build(devkit_root, bundle)
        manifest = bundle / "deployment.json"
        commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=devkit_root).decode().strip()
        version = (devkit_root / "VERSION").read_text().strip()
        source = {"kind": "local", "tag": None, "commit": commit, "snapshot_version": version, "manifest_sha256": deployment.digest(manifest.read_bytes())}
        plan = deployment.plan(target, manifest, source, mode, profile, bound, adaptations, resolutions)
        return deployment.apply(target, plan) if apply else plan


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("operation", choices=("init", "update", "build"))
    parser.add_argument("--target", required=True)
    parser.add_argument("--devkit-root", required=True)
    parser.add_argument("--provider", choices=sorted(deployment.PROVIDERS), required=True)
    parser.add_argument("--mode", choices=("github", "strict"), required=True)
    parser.add_argument("--profile", choices=("repo", "project_root"), default="repo")
    parser.add_argument("--adaptations", required=True, help="Reviewed project content, not generated by this mechanical helper")
    parser.add_argument("--resolutions")
    parser.add_argument("--apply", action="store_true", help="Apply the exact reviewed plan; omission prints plan only")
    args = parser.parse_args()
    try:
        result = local(args.target, args.devkit_root, args.provider, args.mode, args.profile, deployment.load(args.adaptations), deployment.load(args.resolutions) if args.resolutions else None, args.apply)
        print(json.dumps(result))
        return 0
    except deployment.Conflict as exc:
        parser.exit(2, str(exc) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
