"""Regenerate compatibility/discovery wrappers from the shared inventory.

No canonical file is generated or overwritten. Use --check in CI.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def render(entry: dict) -> str:
    source, destination = entry["source"], entry["destination"]
    if source.endswith(".py"):
        return ('"""Generated compatibility wrapper; edit the canonical source instead."""\n'
                'from pathlib import Path\nimport runpy\n'
                f'runpy.run_path(str(Path(__file__).resolve().parents[4] / "{destination}"), run_name="__main__")\n')
    frontmatter = entry.get("discovery_frontmatter", "")
    title = Path(source).stem.replace("_", " ")
    text = frontmatter + f"# {title} — Generated Wrapper\n\n"
    text += f"<!-- Harness source: {destination} -->\n"
    text += "Generated by `.mt-agent-devkit/scripts/generate_wrappers.py`; do not edit.\n\n"
    if "Read_On_Demand" in source:
        text += (f"This file contains no rules. Read only the triggered numbered section from `{destination}`\n"
                 "with `python .mt-agent-devkit/scripts/read_section.py`; preserve the section\n"
                 "number in the citation. Do not load the complete on-demand file at startup.\n")
    else:
        text += (f"Before acting, load `{destination}` and follow its read routing. Reading this\n"
                 "wrapper alone does not satisfy any mandatory-read gate.\n")
        if "Bootstrap" in source:
            text += "Read the canonical bootstrap in full. Every section is mandatory.\n"
    text += ("\nUse the already selected provider adapter and supplied runtime bindings.\n"
             "Never load another provider's adapter to satisfy a shared reference.\n")
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    inventory = json.loads((ROOT / ".mt-agent-devkit/contracts/migration-inventory.json").read_text())
    mismatches = []
    for entry in inventory["files"]:
        if entry["ownership"] != "generated-wrapper":
            continue
        path = ROOT / entry["source"]
        expected = render(entry)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                mismatches.append(entry["source"])
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
    for path in mismatches:
        print(f"[ERROR] {path}: generated wrapper drift")
    return int(bool(mismatches))


if __name__ == "__main__":
    raise SystemExit(main())
